addexit

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -9,11 +9,11 @@ steps:
     key: 'step1'
   - wait: ~
   - command: |
-      if [ $(buildkite-agent step get "outcome" --step "step1") == "soft_failed" ]; then
+      if [ $(buildkite-agent step get "outcome" --step "step1") == "failed" ]; then
          cat <<- YAML | buildkite-agent pipeline upload 
          steps:
            - label: "Notify slack about soft failed step"
-             command: echo "Notifying slack about the soft_failed step"
+             command: echo "Notifying slack about the soft_failed step" && exit 1
              notify:
                - slack: "@jy"
       YAML
