la

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -1,3 +1,21 @@
+notify:
+  # Notify user
+  - slack: "@jy"
+    if: build.state == "passed"
+    
 steps:
-  - label: "Setup and Trigger Failure"
-    command: "./src/trigger.sh"
+  - command: exit -1
+    soft_fail: true
+    key: 'step1'
+  - wait: ~
+  - command: |
+      if [ $(buildkite-agent step get "outcome" --step "step1") == "soft_failed" ]; then
+         cat <<- YAML | buildkite-agent pipeline upload 
+         steps:
+           - label: "Notify slack about soft failed step"
+             command: echo "Notifying slack about the soft_failed step"
+             notify:
+               - slack: "@jy"
+           - label: "Exit with error"
+             command: exit 1
+      YAML
